	list p=16f648a
	include "p16f648a.inc"

	__CONFIG _BODEN_OFF & _CP_OFF & _MCLRE_OFF & _WDT_OFF & _PWRTE_ON & _LVP_OFF & _INTOSC_OSC_NOCLKOUT

	ORG	0000H
	GOTO	MAIN

	ORG	0004H
	RETFIE

MAIN
	BSF	STATUS,RP0			; switch bank
	MOVLW	0FFH
	MOVWF	TRISA			; ALL INPUT

	END
